---
- hosts: servers
  become: True
  tasks:
          - name: Installing service
            yum:
                    name: "httpd"
                    state: "present"

          - name: Starting service
            service:
                    name: httpd
                    state: started
                    enabled: True

          - name: Deploy static html page
            copy: 
            src: index.html
            dest: /var/www/html/
